names = input("Enter names")
print(names)
print()
phone =int(input("Enter mobile number"))
print(phone)
age = int(input("age"))
print(age)
print()
cost_price = int(input("Price of Phone"))
buying_price = int(input("Enter buying price"))
selling_price = int(input("Enter selling price"))
print(" What are uour goals for this class-long term goal?")
goals = input("What would you like to be...when all is said and done?")
print(goals)
